-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Recipe_ingredient CASCADE;
